/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get drivers list
         * @description Retrieve a paginated list of drivers with filtering options
         */
        get: operations["get_Drivers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rides/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a ride
         * @description Submit a new ride request
         */
        post: operations["post_RidesRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * (Frontend-called) GET /api/alerts
         * @description Route called by frontend - needs backend implementation
         */
        get: operations["get_api_alerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * (Frontend-called) GET /api/analytics
         * @description Route called by frontend - needs backend implementation
         */
        get: operations["get_api_analytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * (Frontend-called) GET /api/bookings
         * @description Route called by frontend - needs backend implementation
         */
        get: operations["get_api_bookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * (Frontend-called) GET /api/metrics
         * @description Route called by frontend - needs backend implementation
         */
        get: operations["get_api_metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pricing/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * (Frontend-called) GET /api/pricing/profiles
         * @description Route called by frontend - needs backend implementation
         */
        get: operations["get_api_pricing_profiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pricing/taxi-fares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * (Frontend-called) GET /api/pricing/taxi-fares
         * @description Route called by frontend - needs backend implementation
         */
        get: operations["get_api_pricing_taxifares"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pricing/tnvs-fares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * (Frontend-called) GET /api/pricing/tnvs-fares
         * @description Route called by frontend - needs backend implementation
         */
        get: operations["get_api_pricing_tnvsfares"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Driver: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            phone: string;
            /** @enum {string} */
            status: "active" | "inactive" | "suspended";
            rating: number;
            /** Format: date-time */
            createdAt: string;
            vehicleInfo?: {
                /** @enum {string} */
                type?: "motorcycle" | "car" | "suv" | "taxi";
                model?: string;
                plateNumber?: string;
                color?: string;
                year?: number;
            };
            location?: {
                latitude?: number;
                longitude?: number;
                address?: string;
            };
        };
        Pagination: {
            page?: number;
            limit?: number;
            total?: number;
            totalPages?: number;
        };
        Error: {
            error?: string;
            message?: string;
            code?: number;
        };
        GenericObject: {
            [key: string]: unknown;
        };
        StandardError: {
            message: string;
            code?: string;
        };
        DriversGETRequest: {
            ok: boolean;
            data?: {
                [key: string]: unknown;
            };
        };
        RideRequest: {
            pickup: {
                lat: number;
                lng: number;
                address: string;
            };
            destination: {
                lat: number;
                lng: number;
                address: string;
            };
            /** @enum {string} */
            serviceType: "standard" | "premium" | "shared" | "ride_4w" | "ride_2w" | "send_delivery";
            /** Format: date-time */
            scheduledTime?: string;
            passengerCount?: number;
            specialRequests?: string;
        };
        RideResponse: {
            /** Format: uuid */
            rideId: string;
            bookingReference?: string;
            estimatedFare?: number;
            /** Format: date-time */
            estimatedArrival?: string;
            /** @enum {string} */
            status: "pending" | "searching" | "matched" | "assigned" | "en_route" | "arrived" | "in_progress" | "completed" | "cancelled";
            driver?: components["schemas"]["Driver"];
            surgeMultiplier?: number;
        };
        RegionAssignmentRequest: {
            /** Format: uuid */
            userId: string;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            /** @enum {string} */
            role?: "regional_manager" | "supervisor" | "operator";
            permissions?: string[];
        };
        RegionAssignmentResponse: {
            success: boolean;
            message?: string;
            assignment: {
                /** Format: uuid */
                regionId: string;
                /** Format: uuid */
                userId: string;
                /** Format: date-time */
                assignedAt: string;
                role?: string;
                permissions?: string[];
            };
        };
        DriversListResponse: {
            data: components["schemas"]["Driver"][];
            pagination: components["schemas"]["Pagination"];
            totalActive?: number;
            totalInactive?: number;
            averageRating?: number;
        };
        DriverUpdateRequest: {
            /** @enum {string} */
            status?: "active" | "inactive" | "suspended";
            phone?: string;
            /** Format: email */
            email?: string;
            vehicleInfo?: {
                /** @enum {string} */
                type?: "motorcycle" | "car" | "suv" | "taxi";
                model?: string;
                plateNumber?: string;
                color?: string;
            };
        };
        AnalyticsGetResponse: {
            ok?: boolean;
            data?: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        BookingsGetResponse: {
            ok?: boolean;
            data?: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        DriversGetResponse: {
            ok?: boolean;
            data?: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        MetricsGetResponse: {
            ok?: boolean;
            data?: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        PricingProfilesGetResponse: {
            ok?: boolean;
            data?: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        RidesRequestPostRequest: {
            [key: string]: unknown;
        };
        RidesRequestPostResponse: {
            ok?: boolean;
            data?: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        AlertsGetResponse: {
            ok?: boolean;
            data?: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        PricingTaxiFaresGetResponse: {
            ok?: boolean;
            data?: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        PricingTnvsFaresGetResponse: {
            ok?: boolean;
            data?: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_Drivers: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Number of items per page */
                limit?: number;
                /** @description Filter by driver status */
                status?: "active" | "inactive" | "suspended";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriversGetResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_RidesRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /** @example {
                 *       "ok": true,
                 *       "data": {
                 *         "note": "replace with real request shape"
                 *       }
                 *     } */
                "application/json": {
                    pickup: {
                        lat: number;
                        lng: number;
                        address: string;
                    };
                    destination: {
                        lat: number;
                        lng: number;
                        address: string;
                    };
                    /** @enum {string} */
                    serviceType: "standard" | "premium" | "shared";
                    /**
                     * Format: date-time
                     * @description Optional scheduled pickup time
                     */
                    scheduledTime?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RidesRequestPostResponse"];
                };
            };
            /** @description OK */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RidesRequestPostResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandardError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_api_alerts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertsGetResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_api_analytics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsGetResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_api_bookings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingsGetResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_api_metrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsGetResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_api_pricing_profiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricingProfilesGetResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_api_pricing_taxifares: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricingTaxiFaresGetResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_api_pricing_tnvsfares: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricingTnvsFaresGetResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
